include::doc/includes.adoc[]

= buildSrcVersions

Painless Gradle dependencies management from your IDE.

This Gradle plugin adds a **:buildSrcVersions** task to your build that

- Extract all your dependencies to {root}/buildSrc/src/main/kotlin/Versions.kt[buildSrc/src/main/kotlin/Versions.kt].
- Tell you about available updates inside {root}/buildSrc/src/main/kotlin/Versions.kt[buildSrc/src/main/kotlin/Versions.kt].




== Getting Started

Edit your root `build.gradle(.kts)` file

```kotlin
buildscript {
    //...
}
plugins {
  id("jmfayard.github.io.gradle-kotlin-dsl-libs") version "{pluginVersion}"
}
// Don't put any code before the buildscripts {} and plugins {} block
```


== Extract your dependencies


```bash
$ ./gradlew -q buildSrcVersions
> :dependencyUpdates
> :buildSrcVersions
    new file:   buildSrc/build.gradle.kts
    new file:   buildSrc/.gitignore
    new file:   buildSrc/src/main/kotlin/Versions.kt
    new file:   buildSrc/src/main/kotlin/Libs.kt
```


== IDE integration

TODO: screencast



```kotlin
dependencies {
    implementation(Libs.okio)
    implementation(Libs.com_squareup_moshi_moshi)
    implementation(Libs.retrofit)
}
```



== Update your dependencies

```bash
$ ./gradlew -q buildSrcVersions
> :dependencyUpdates
> :buildSrcVersions
       modified:   buildSrc/src/main/kotlin/Versions.kt
$ echo "Tip: commit your changes before you update the dependencies"
```

TODO: screencast

== Prerequisites

- Kotlin, Java and Android projects.
- IntelliJ >= 2008.03+ Android Studio 3.2+.
- IDE support for both `build.gradle` and `build.gradle.kts` scripts.

== Changelog

See Changelog.md

== Contributors

include::doc/contributors.adoc[]

== Contributing

- This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details
- Explain your use case and start the discussion before your submit a pull-request
- Run the automated tests with
- Format your code

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.


== Acknowledgments

This project sits on the shoulder of giants:

