import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * [gradle-versions-plugin website](https://github.com/ben-manes/gradle-versions-plugin) */
    const val gradle_versions_plugin: String =
            "com.github.ben-manes:gradle-versions-plugin:" + Versions.gradle_versions_plugin

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    const val com_gradle_plugin_publish_gradle_plugin: String =
            "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:" + Versions.com_gradle_plugin_publish_gradle_plugin

    /**
     * [moshi website](https://github.com/square/moshi) */
    const val com_squareup_moshi_moshi: String =
            "com.squareup.moshi:moshi:" + Versions.com_squareup_moshi_moshi

    /**
     * [okio website](https://github.com/square/okio/) */
    const val okio: String = "com.squareup.okio:okio:" + Versions.okio

    /**
     * [converter-moshi website](https://github.com/square/retrofit/) */
    const val converter_moshi: String =
            "com.squareup.retrofit2:converter-moshi:" + Versions.com_squareup_retrofit2

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String =
            "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

    /**
     * [kotlinpoet website](http://github.com/square/kotlinpoet/) */
    const val kotlinpoet: String = "com.squareup:kotlinpoet:" + Versions.kotlinpoet

    /**
     * [kotlintest-runner-junit5 website](http://www.github.com/kotlintest/kotlintest) */
    const val kotlintest_runner_junit5: String =
            "io.kotlintest:kotlintest-runner-junit5:" + Versions.kotlintest_runner_junit5

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String =
            "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:" + Versions.org_gradle_kotlin_kotlin_dsl_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * [kotlin-reflect website](https://kotlinlang.org/) */
    const val kotlin_reflect: String =
            "org.jetbrains.kotlin:kotlin-reflect:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-sam-with-receiver website](https://kotlinlang.org/) */
    const val kotlin_sam_with_receiver: String =
            "org.jetbrains.kotlin:kotlin-sam-with-receiver:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" + Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin
}
